### ISSUE TITLE
ST3 (Build 3009): plugin inactive in the menu

### ISSUE THREAD

**Issue by mogilny** [wbond/sublime_prefixr#15]
First of all, thank you for your beautiful plugins for sublime!

Running the portable ST3, Build 3009 on a Win7 / 32-Bit I get follwoing error on the start-up in the console:

---

reloading plugin Prefixr.Prefixr
Traceback (most recent call last):
  File "C:\Portable Apps\Sublime Text 3\sublime_plugin.py", line 70, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 854, in _load_module
  File "<frozen importlib._bootstrap>", line 981, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Portable Apps\Sublime Text 3\Data\Packages\Prefixr\Prefixr.py", line 162
    except (urllib2.HTTPError) as (e):
                                  ^
SyntaxError: invalid syntax

---

As an effect of this the Prefixr Menu is there, but inactive (grayed out). I did the installation via you (again beautiful) Package Loader plugin and manualy. Both installations with the same effect.

Hope that the problem is not to hard to solve ;-)

**Comment by brunowego** [comment]
Yes, I get the problem too...

**Comment by dndrsn** [comment]
Tried using 2to3 on Prefixr.py to update syntax and libraries for Python 3.  Fixed the syntax problems, but surfaced new ones with the ST3 API changes.  Specifically changes to begin_end() and end_edit(), and perhaps others.
